name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.7
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
        clean: true  # Clean the working tree before checkout
        show-progress: true  # Show download progress

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: olmobarberis/peppermint
        tags: |
          type=ref,event=tag
          type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/main' }}
          type=raw,value={{branch}}-{{sha}}-${{ steps.date.outputs.date }},enable=${{ github.ref != 'refs/heads/main' && github.ref_type != 'tag' }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}