name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build from'
        required: true
        default: 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true
        show-progress: true
        ref: ${{ github.event.inputs.ref || github.ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract branch or tag name
      shell: bash
      run: |
        if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
          echo "REF_TYPE=tag" >> $GITHUB_ENV
          echo "REF_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "refs/heads/"* ]]; then
          echo "REF_TYPE=branch" >> $GITHUB_ENV
          echo "REF_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        else
          echo "REF_TYPE=other" >> $GITHUB_ENV
          echo "REF_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        fi
        echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: olmobarberis/peppermint
        tags: |
          type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/main' }}
          type=raw,value=${{ env.REF_NAME }},enable=${{ env.REF_TYPE == 'tag' }}
          type=raw,value=${{ env.REF_NAME }}-${{ env.SHA_SHORT }},enable=${{ env.REF_TYPE == 'branch' && env.REF_NAME != 'main' }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}