name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or your default branch name
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: olmobarberis/peppermint
        tags: |
          type=ref,event=tag
          type=raw,value=nightly,enable=${{ github.ref_type != 'tag' }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}