name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build from'
        required: true
        default: 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true
        show-progress: true
        ref: ${{ github.event.inputs.ref || github.ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract branch or tag name
      shell: bash
      run: echo "REF_NAME=$(echo ${GITHUB_REF#refs/*/})" >> $GITHUB_ENV

    - name: Generate Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: olmobarberis/peppermint
        tags: |
          type=raw,value=nightly,enable=${{ github.ref == 'refs/heads/main' }}
          type=raw,value=${{ env.REF_NAME }},enable=${{ github.ref != 'refs/heads/main' }}
          type=sha,prefix=${{ env.REF_NAME }}-

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}